require 'hoe'
require './lib/pixelart/version.rb'

Hoe.spec 'pixelart' do

  self.version = Pixelart::VERSION

  self.summary = "pixelart - yes, you can! generate your own pixel art images (off-blockchain) using any design (in ascii text) in any colors; incl. 2x/4x/8x zoom for bigger sizes"
  self.description = summary

  self.urls    = { home: 'https://github.com/learnpixelart/pixelart' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ['pixelart-colors'],
    ['chunky_png'],
    ['mini_magick'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
